---
- hosts: webserver
  remote_user: jenkins
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip
      yum: name=python-pip state=present

    - name: install docker-py package
      pip: name=docker-py

    - name: Build Docker image from Dockerfile
      docker_image:
        name: devops_pipeline_demo
        path: docker
        state: build
        
    - name: Running the container
      docker_container:
        image: devops_pipeline_demo:latest
        path: docker
        state: running

    - name: Check if container is running
      shell: docker ps